Ext.define("Soims.model.application.Application", {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'id', type: 'int', mapping: 'ID' },
        { name: 'applicationNumber', mapping: 'ApplicationNumber' },
        { name: 'name', mapping: 'Name' },
        { name: 'discussionTime', mapping: 'DiscussionTime' },
        { name: 'approvalTime', mapping: 'ApprovalTime' },
        { name: 'applicantID', mapping: 'ApplicantID' },
        { name: 'applicantName', mapping: 'ApplicantName' },
        { name: 'charger', mapping: 'Charger' },
        { name: 'chargerID', mapping: 'ChargerID' },
        { name: 'leg', mapping: 'Leg' },
        { name: 'voyage', mapping: 'Voyage' },        
        { name: 'legID', mapping: 'LegID' },
        { name: 'type', mapping: 'Type' },
        { name: 'taskName', mapping: 'TaskName' },
        { name: 'topicID', mapping: 'TopicID' },
        { name: 'bearVoyageTaskID', mapping: 'BearVoyageTaskID' },
        { name: 'voyageReportID', mapping: 'VoyageReportID' },
        { name: 'noOceanTopicID', mapping: 'NoOceanTopicID' },
        { name: 'activityID', mapping: 'ActivityID' },
        { name: 'activityStartTime', mapping: 'ActivityStartTime' },
        { name: 'activityEndTime', mapping: 'ActivityEndTime' },
        { name: 'usingNecessity', mapping: 'UsingNecessity' },
        { name: 'repatriaionNecessity', mapping: 'RepatriaionNecessity' },
        { name: 'commitResultTime', mapping: 'CommitResultTime' },
        { name: 'commitResultForm', mapping: 'CommitResultForm' },
        { name: 'commitResultAmount', mapping: 'CommitResultAmount' },
        { name: 'applyTime', mapping: 'ApplyTime' },
        { name: 'createTime', mapping: 'CreateTime' },
        { name: 'state', mapping: 'State' }      
    ]
});